dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.4.0
  - OpenZeppelin/openzeppelin-contracts@4.2.0
compiler:
  solc:
    remappings: 
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0'
networks:
  development:
    verify: False
  ganache:
    verify: False
  kovan:
    verify: True
dotenv: .env
wallets: 
  from_key: ${PRIVATE_KEY}